---
- name: Configurer MySQL
  template:
    src: ../../templates/my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify:
    - redémarrer MySQL

- name: Create database
  mysql_db:
  name: wordpress
  state: present
  become: true

- name: Set root password for MySQL
  mysql_user:
    name: root
    password: root
    priv: ".:ALL"
    host: localhost

handlers:
- name: Redémarrer MySQL
  service:
    name: mysql
    state: restarted