---
- name: Configure DHCP on Vagrant
  hosts: web-servers
  gather_facts: true
  vars:
    network_interface: eth1
    subnet: 192.168.56.0
    netmask: 255.255.255.0
    range_start: 192.168.56.101
    range_end: 192.168.56.200
    router: 192.168.56.1
    dns_server: 8.8.8.8
  tasks:
    - name: Install DHCP server
      apt:
        name: isc-dhcp-server
        state: present
    - name: Create DHCP config file
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
      notify:
        - restart dhcp
    - name: Configure DHCP service
      service:
        name: isc-dhcp-server
        state: started
        enabled: true
      handlers:
        - name: restart dhcp
          service:
            name: isc-dhcp-server
            state: restarted

