---
- name: Install dependencies
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mysql-server

