---
- name: Installation d'un serveur web
  hosts: web
  remote_user: web
  become: true
  become_method: sudo
  vars_files: 
    - vars.yml
  roles:
    - all
    - serveur-web

- name: Installation d'une base de donnée 
  hosts: db
  remote_user: web
  become: true
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - all
    - database